// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: rank_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phrase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Phrase) Reset() {
	*x = Phrase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phrase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phrase) ProtoMessage() {}

func (x *Phrase) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phrase.ProtoReflect.Descriptor instead.
func (*Phrase) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{0}
}

func (x *Phrase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Phrase) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Rank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date     string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Rank     int32  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	PaidRank int32  `protobuf:"varint,3,opt,name=paidRank,proto3" json:"paidRank,omitempty"`
	Mp       string `protobuf:"bytes,4,opt,name=mp,proto3" json:"mp,omitempty"`
}

func (x *Rank) Reset() {
	*x = Rank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{1}
}

func (x *Rank) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Rank) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Rank) GetPaidRank() int32 {
	if x != nil {
		return x.PaidRank
	}
	return 0
}

func (x *Rank) GetMp() string {
	if x != nil {
		return x.Mp
	}
	return ""
}

type KeyPhrase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phrase *Phrase `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Ranks  []*Rank `protobuf:"bytes,2,rep,name=ranks,proto3" json:"ranks,omitempty"`
}

func (x *KeyPhrase) Reset() {
	*x = KeyPhrase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPhrase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPhrase) ProtoMessage() {}

func (x *KeyPhrase) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPhrase.ProtoReflect.Descriptor instead.
func (*KeyPhrase) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPhrase) GetPhrase() *Phrase {
	if x != nil {
		return x.Phrase
	}
	return nil
}

func (x *KeyPhrase) GetRanks() []*Rank {
	if x != nil {
		return x.Ranks
	}
	return nil
}

// AddPhrase
type AddPhrasesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Phrases []*Phrase `protobuf:"bytes,2,rep,name=phrases,proto3" json:"phrases,omitempty"`
}

func (x *AddPhrasesReq) Reset() {
	*x = AddPhrasesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPhrasesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPhrasesReq) ProtoMessage() {}

func (x *AddPhrasesReq) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPhrasesReq.ProtoReflect.Descriptor instead.
func (*AddPhrasesReq) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{3}
}

func (x *AddPhrasesReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddPhrasesReq) GetPhrases() []*Phrase {
	if x != nil {
		return x.Phrases
	}
	return nil
}

// Ranking
type RankingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Mp    string `protobuf:"bytes,2,opt,name=mp,proto3" json:"mp,omitempty"`
}

func (x *RankingReq) Reset() {
	*x = RankingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingReq) ProtoMessage() {}

func (x *RankingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingReq.ProtoReflect.Descriptor instead.
func (*RankingReq) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{4}
}

func (x *RankingReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RankingReq) GetMp() string {
	if x != nil {
		return x.Mp
	}
	return ""
}

type RankingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPhrases []*KeyPhrase `protobuf:"bytes,1,rep,name=keyPhrases,proto3" json:"keyPhrases,omitempty"`
}

func (x *RankingResp) Reset() {
	*x = RankingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingResp) ProtoMessage() {}

func (x *RankingResp) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingResp.ProtoReflect.Descriptor instead.
func (*RankingResp) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{5}
}

func (x *RankingResp) GetKeyPhrases() []*KeyPhrase {
	if x != nil {
		return x.KeyPhrases
	}
	return nil
}

// AddRank
type AddRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PhraseId uint64 `protobuf:"varint,2,opt,name=phraseId,proto3" json:"phraseId,omitempty"`
	Rank     int32  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	PaidRank int32  `protobuf:"varint,4,opt,name=paidRank,proto3" json:"paidRank,omitempty"`
	Mp       string `protobuf:"bytes,5,opt,name=mp,proto3" json:"mp,omitempty"`
}

func (x *AddRankReq) Reset() {
	*x = AddRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRankReq) ProtoMessage() {}

func (x *AddRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRankReq.ProtoReflect.Descriptor instead.
func (*AddRankReq) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{6}
}

func (x *AddRankReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddRankReq) GetPhraseId() uint64 {
	if x != nil {
		return x.PhraseId
	}
	return 0
}

func (x *AddRankReq) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *AddRankReq) GetPaidRank() int32 {
	if x != nil {
		return x.PaidRank
	}
	return 0
}

func (x *AddRankReq) GetMp() string {
	if x != nil {
		return x.Mp
	}
	return ""
}

// OldRanks
type OldRanksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From uint32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   uint32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *OldRanksReq) Reset() {
	*x = OldRanksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OldRanksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OldRanksReq) ProtoMessage() {}

func (x *OldRanksReq) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OldRanksReq.ProtoReflect.Descriptor instead.
func (*OldRanksReq) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{7}
}

func (x *OldRanksReq) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *OldRanksReq) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

type OldRanksResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phrase   string   `protobuf:"bytes,2,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Products []string `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *OldRanksResp) Reset() {
	*x = OldRanksResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OldRanksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OldRanksResp) ProtoMessage() {}

func (x *OldRanksResp) ProtoReflect() protoreflect.Message {
	mi := &file_rank_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OldRanksResp.ProtoReflect.Descriptor instead.
func (*OldRanksResp) Descriptor() ([]byte, []int) {
	return file_rank_message_proto_rawDescGZIP(), []int{8}
}

func (x *OldRanksResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OldRanksResp) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *OldRanksResp) GetProducts() []string {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_rank_message_proto protoreflect.FileDescriptor

var file_rank_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2c, 0x0a, 0x06, 0x50, 0x68,
	0x72, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x5a, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x69, 0x64,
	0x52, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x69, 0x64,
	0x52, 0x61, 0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x6d, 0x70, 0x22, 0x53, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x50, 0x68, 0x72, 0x61, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x52,
	0x06, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x61,
	0x6e, 0x6b, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x22, 0x4d, 0x0a, 0x0d, 0x41, 0x64, 0x64,
	0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x26, 0x0a, 0x07, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x52,
	0x07, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6d, 0x70, 0x22, 0x3e, 0x0a, 0x0b,
	0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x0a, 0x6b,
	0x65, 0x79, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65,
	0x52, 0x0a, 0x6b, 0x65, 0x79, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x22, 0x80, 0x01, 0x0a,
	0x0a, 0x41, 0x64, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72,
	0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x69, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x69, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6d, 0x70, 0x22,
	0x31, 0x0a, 0x0b, 0x4f, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x0c, 0x4f, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x68, 0x72,
	0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rank_message_proto_rawDescOnce sync.Once
	file_rank_message_proto_rawDescData = file_rank_message_proto_rawDesc
)

func file_rank_message_proto_rawDescGZIP() []byte {
	file_rank_message_proto_rawDescOnce.Do(func() {
		file_rank_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_rank_message_proto_rawDescData)
	})
	return file_rank_message_proto_rawDescData
}

var file_rank_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rank_message_proto_goTypes = []interface{}{
	(*Phrase)(nil),        // 0: main.Phrase
	(*Rank)(nil),          // 1: main.Rank
	(*KeyPhrase)(nil),     // 2: main.KeyPhrase
	(*AddPhrasesReq)(nil), // 3: main.AddPhrasesReq
	(*RankingReq)(nil),    // 4: main.RankingReq
	(*RankingResp)(nil),   // 5: main.RankingResp
	(*AddRankReq)(nil),    // 6: main.AddRankReq
	(*OldRanksReq)(nil),   // 7: main.OldRanksReq
	(*OldRanksResp)(nil),  // 8: main.OldRanksResp
}
var file_rank_message_proto_depIdxs = []int32{
	0, // 0: main.KeyPhrase.phrase:type_name -> main.Phrase
	1, // 1: main.KeyPhrase.ranks:type_name -> main.Rank
	0, // 2: main.AddPhrasesReq.phrases:type_name -> main.Phrase
	2, // 3: main.RankingResp.keyPhrases:type_name -> main.KeyPhrase
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rank_message_proto_init() }
func file_rank_message_proto_init() {
	if File_rank_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rank_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phrase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPhrase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPhrasesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OldRanksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OldRanksResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rank_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rank_message_proto_goTypes,
		DependencyIndexes: file_rank_message_proto_depIdxs,
		MessageInfos:      file_rank_message_proto_msgTypes,
	}.Build()
	File_rank_message_proto = out.File
	file_rank_message_proto_rawDesc = nil
	file_rank_message_proto_goTypes = nil
	file_rank_message_proto_depIdxs = nil
}
